cp  ./PR/PR_agonist/targets/1SQN/dock_originalPDB/run.NRs/ligands/energy-4 PR_agonist_energy-4
cp  ./PR/PR_antagonist/targets/2OVH/dock_originalPDB/run.NRs/ligands/energy-4 PR_antagonist_energy-4
cp  ./GR/GR_agonist/targets/3K22/dock_originalPDB/run.NRs/ligands/energy-4 GR_agonist_energy-4
cp  ./GR/GR_antagonist/targets/1NHZ/dock_originalPDB/run.NRs/ligands/energy-4 GR_antagonist_energy-4
cp  ./ER_alpha/ER_alpha_agonist/targets/1X7R/dock_originalPDB/run.NRs/ligands/energy-4 ER_alpha_agonist_energy-4
cp  ./ER_alpha/ER_alpha_antagonist/targets/1XP1/dock_originalPDB/run.NRs/ligands/energy-4 ER_alpha_antagonist_energy-4
cp  ./RAR_alpha/RAR_alpha_antagonist/targets/1DKF/dock_originalPDB/run.NRs/ligands/energy-4 RAR_alpha_antagonist_energy-4
cp  ./RAR_alpha/RAR_alpha_agonist/targets/3KMR/dock_originalPDB/run.NRs/ligands/energy-4 RAR_alpha_agonist_energy-4
cp  ./ER_beta/ER_beta_antagonist/targets/1L2J/dock_originalPDB/run.NRs/ligands/energy-4 ER_beta_antagonist_energy-4
cp  ./ER_beta/ER_beta_agonist/targets/3OLL/dock_originalPDB/run.NRs/ligands/energy-4 ER_beta_agonist_energy-4
cp  ./MR/MR_agonist/targets/2A3I/dock_originalPDB/run.NRs/ligands/energy-4 MR_agonist_energy-4
cp  ./MR/MR_antagonist/targets/3VHV/dock_originalPDB/run.NRs/ligands/energy-4 MR_antagonist_energy-4
cp  ./RXR_alpha/RXR_alpha_antagonist/targets/3NSQ/dock_originalPDB/run.NRs/ligands/energy-4 RXR_alpha_antagonist_energy-4
cp  ./RXR_alpha/RXR_alpha_agonist/targets/1MV9/dock_originalPDB/run.NRs/ligands/energy-4 RXR_alpha_agonist_energy-4
cp  ./PPAR_gamma/PPAR_gamma_agonist/targets/3BC5/dock_originalPDB/run.NRs/ligands/energy-4 PPAR_gamma_agonist_energy-4
cp  ./PPAR_gamma/PPAR_gamma_antagonist/targets/3E00/dock_prot_mol2/run.NRs/ligands/energy-4 PPAR_gamma_antagonist_energy-4
cp  ./PPAR_alpha/PPAR_alpha_antagonist/targets/1KKQ/dock_originalPDB/run.NRs/ligands/energy-4 PPAR_alpha_antagonist_energy-4
cp  ./PPAR_alpha/PPAR_alpha_agonist/targets/2P54/dock_originalPDB/run.NRs/ligands/energy-4 PPAR_alpha_agonist_energy-4
cp  ./ROR_gamma/ROR_gamma_antagonist/targets/3B0W/dock_originalPDB/run.NRs/ligands/energy-4 ROR_gamma_antagonist_energy-4
cp  ./ROR_gamma/ROR_gamma_agonist/targets/3L0L/dock_originalPDB/run.NRs/ligands/energy-4 ROR_gamma_agonist_energy-4
